/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function init(buf: Buffer): Buffer
export function run(): void
export function read(): Promise<Buffer>
export function sendMessage(socketId: string, payload: Buffer): void
